#博客名称
title: 阿甘的博客
#副标题
subtitle: 一天进步一点
#简介
description: 记录生活点滴
#博客作者
author: 阿甘
#博客语言
language: zh-CN
#时区
timezone:

#博客地址,与申请的GitHub一致
url: http://978420544.github.io
root: /
#博客链接格式
permalink: :year/:month/:day/:title/
permalink_defaults:

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

category_map:
    Java: java
    Spring: spring
    Hexo: hexo
    设计模式: design
    生活: life
    互联网: internet
tag_map:
  Java: java
  设计模式: design
  多线程: thread
  Shiro: shiro
  Spring: spring
  Hexo: hexo
  Simpleblock: simpleblock 
  Solr: solr
  生活: life
  职场: work
  鸡汤: soul

#日期格式
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Extensions
Plugins:
- hexo-generator-feed
- hexo-generator-sitemap
- hexo-generator-baidu-sitemap
#Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20
#sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

#分页，每页文章数量
per_page: 6
pagination_dir: page

#博客主题
theme: simpleblock

#发布设置
deploy: 
  type: git
  #elfwalk改为你的github用户名
  #repository: git@github.com:978420544/978420544.github.io.git
  #branch: master
  repo:
      github: git@github.com:978420544/978420544.github.io.git,master
      coding: git@git.coding.net:agandeboke/agandeboke.coding.me.git,master