## Services
google_analytics:
duoshuo:

## Meta
rss: https://978420544.github.io/atom.xml
favicon: /favicon.png
icon: /favicon.png
source_url: https://github.com/978420544/978420544.github.io/tree/source/source/
license:
  name: 'CC BY-NC-SA 3.0'
  url: 'http://creativecommons.org/licenses/by-nc-sa/3.0/cn'

## Menus
menus:
  '首页': /
  '归档': /archives
  '简历': /resume
  '推荐': /
  '关于阿甘': /

right_menus:
  'RSS': /atom.xml
  'fork on Github':
    target: '_blank'
    href: 'https://github.com/978420544'

## Banners && Widgets
banners:
  jade: |
    a(href='https://github.com/978420544') 《斗破苍穹》三十年河西三十年河东，莫欺少年穷！

widgets:
  -
    markdown: |
      阿甘，河南人，技术宅，生于1993,12,23。

      * 毕业于[郑州轻工业学院](http://www.zzuli.edu.cn/)
      * 一个努力前进的[菜鸟](https://github.com/978420544/Demo)
      * 一个默默奋斗的潜力股
      * 向着明天，一步一步的男人
      * 在 [Github](https://github.com/978420544) 上积极参与开源社区
      
  - categories: true

  -
    tags: true

  -
    archives: true

  -
    copyright: true

## SNS (Work in progress)
sns:
  qq: '978420544'
  qun: '61137226'
  v2ex: 'jybox'
  mobile: '18321371259'
  github: '978420544'
  keybase: '978420544'
  zhihu: '978420544'
  google_plus: '+978420544'
  segmentfault: '978420544'
  twitter: '978420544'
  bitcoin: '13v2BTCMZMHg5v87susgg86HFZqXERuwUd'
